### ISSUE TITLE
zsh: ./keepassxc-dmenu: bad interpreter: /bin/tclsh: no such file or directory

### ISSUE THREAD

**Issue by EliaHKM** [natrys/keepassxc-dmenu#3]
Hi,
Like the title said I can't run it
help me please

**Comment by natrys** [comment]
Which OS? Does your environment satisfy the requirements (`tcl` and `expect` in particular)?

Try doing:
```sh
which tclsh
```

If tcl is already installed, then the interpreter executable is probably somewhere other than `/bin/tclsh`. Maybe you can try replacing the first line of `keepassxc-dmenu` to use env (e.g. change `#!/bin/tclsh` to `#!/usr/bin/env tclsh`.

**Comment by EliaHKM** [comment]
it gives me this :
`/usr/bin/tclsh`
after replacing it , it gives me this 
`✦ ❯ ./keepassxc-dmenu
send: spawn id exp8 not open
    while executing
"send -- "$kpxc_pw\r""
    (procedure "enter_pw" line 4)
    invoked from within
"enter_pw $kpxc_pw"
    (file "./keepassxc-dmenu" line 128)
`

**Comment by natrys** [comment]
Was there any graphical prompt asking you for password? There should be one.

If there wasn't one, make sure you have pinentry installed (I recommend pinentry-qt). And then, as noted in readme, specify `kpxc_pinentry` in the config file at `~/.config/keepassxc-dmenu/config`.

If you already do have it installed, what does `which pinentry-qt` say?

**Comment by EliaHKM** [comment]
yes there is one I've installed  pinentry-qt
which pinentry-qt gives me this
`/usr/bin/pinentry-qt
`

**Comment by natrys** [comment]
And once you run `./keepassxc-dmenu`, does any password prompt show up?

It's also imperative that you set up the config like how it is in the readme. Am I correct in assuming you have your keepassxc password database in `~/Passwords.kdbx` file? Are you certain your keepassxc installation comes with the command line tool? What does `which keepassxc-cli` say?

**Comment by EliaHKM** [comment]
yeah I have keepassxc-cli 
this is the output of which keepassxc-cli
`/usr/bin/keepassxc-cli`
It shows up
and I've done everything in the readme

**Comment by EliaHKM** [comment]
I'm using devuan 3.1

**Comment by natrys** [comment]
The 5th line in `keepassxc-dmenu` has this line:

```
# exp_internal 1
```

Uncomment the line and run it again please. Will give a bit more information on where it's erroring. Then paste the last few lines of the output (be careful not to include any line containing password).

**Comment by EliaHKM** [comment]
`❯ ./keepassxc-dmenu
parent: waiting for sync byte
parent: telling child to go ahead
parent: now unsynchronized from child
spawn: returns {8843}

expect: does "" (spawn_id exp4) match glob pattern "OK"? no

expect: does "qt5ct: using qt5ct plugin" (spawn_id exp4) match glob pattern "OK"? no

expect: does "qt5ct: using qt5ct plugin\r\n" (spawn_id exp4) match glob pattern "OK"? no

expect: does "qt5ct: using qt5ct plugin\r\nOK Pleased to meet you" (spawn_id exp4) match glob pattern "OK"? yes
expect: set expect_out(0,string) "OK"
expect: set expect_out(spawn_id) "exp4"
expect: set expect_out(buffer) "qt5ct: using qt5ct plugin\r\nOK"
send: sending "SETDESC Enter Password for /home/darkeye/Documents/Passwords-29-1-2019.kdbx:\r" to { exp4 }

expect: does " Pleased to meet you" (spawn_id exp4) match glob pattern "OK"? no

expect: does " Pleased to meet youSETDESC Enter Password for /home/darkeye/Documents/Passwords-29-1-2019.kdbx:\r\n" (spawn_id exp4) match glob pattern "OK"? no

expect: does " Pleased to meet youSETDESC Enter Password for /home/darkeye/Documents/Passwords-29-1-2019.kdbx:\r\n\r\n" (spawn_id exp4) match glob pattern "OK"? no

expect: does " Pleased to meet youSETDESC Enter Password for /home/darkeye/Documents/Passwords-29-1-2019.kdbx:\r\n\r\nOK" (spawn_id exp4) match glob pattern "OK"? yes
expect: set expect_out(0,string) "OK"
expect: set expect_out(spawn_id) "exp4"
expect: set expect_out(buffer) " Pleased to meet youSETDESC Enter Password for /home/darkeye/Documents/Passwords-29-1-2019.kdbx:\r\n\r\nOK"
send: sending "GETPIN\r" to { exp4 }

expect: does "" (spawn_id exp4) match glob pattern "OK"? no
"cancelled"? no

expect: does "GETPIN\r\n" (spawn_id exp4) match glob pattern "OK"? no
"cancelled"? no

expect: does "GETPIN\r\n\r\n" (spawn_id exp4) match glob pattern "OK"? no
"cancelled"? no

expect: does "GETPIN\r\n\r\nD **********\r\nOK\r\n" (spawn_id exp4) match glob pattern "OK"? yes
expect: set expect_out(0,string) "OK"
expect: set expect_out(spawn_id) "exp4"
expect: set expect_out(buffer) "GETPIN\r\n\r\nD **********\r\nOK"
send: sending "BYE\r" to { exp4 }
parent: waiting for sync byte
parent: telling child to go ahead
parent: now unsynchronized from child
spawn: returns {8945}

expect: does "" (spawn_id exp7) match glob pattern "Enter password"? no

expect: does "Invalid command open.\r\n" (spawn_id exp7) match glob pattern "Enter password"? no

expect: does "Invalid command open.\r\nUsage: keepassxc-cli [options] command\r\nKeePassXC command line interface.\r\n\r\nAvailable commands:\r\nadd            Add a new entry to a database.\r\nclip           Copy an entry's password to the clipboard.\r\ndiceware       Generate a new random diceware passphrase.\r\nedit           Edit an entry.\r\nestimate       Estimate the entropy of a password.\r\nextract        Extract and print the content of a database.\r\ngenerate       Generate a new random password.\r\nlocate         Find entries quickly.\r\nls             List database entries.\r\nmerge          Merge two databases.\r\nrm             Remove an entry from the database.\r\nshow           Show an entry's information.\r\n\r\n\r\nOptions:\r\n  -h, --help     Displays this help.\r\n  -v, --version  Displays version information.\r\n\r\nArguments:\r\n  command        Name of the command to execute.\r\n" (spawn_id exp7) match glob pattern "Enter password"? no
expect: read eof
expect: set expect_out(spawn_id) "exp7"
expect: set expect_out(buffer) "Invalid command open.\r\nUsage: keepassxc-cli [options] command\r\nKeePassXC command line interface.\r\n\r\nAvailable commands:\r\nadd            Add a new entry to a database.\r\nclip           Copy an entry's password to the clipboard.\r\ndiceware       Generate a new random diceware passphrase.\r\nedit           Edit an entry.\r\nestimate       Estimate the entropy of a password.\r\nextract        Extract and print the content of a database.\r\ngenerate       Generate a new random password.\r\nlocate         Find entries quickly.\r\nls             List database entries.\r\nmerge          Merge two databases.\r\nrm             Remove an entry from the database.\r\nshow           Show an entry's information.\r\n\r\n\r\nOptions:\r\n  -h, --help     Displays this help.\r\n  -v, --version  Displays version information.\r\n\r\nArguments:\r\n  command        Name of the command to execute.\r\n"
send: sending "**********\r" to { exp7 send: spawn id exp7 not open
    while executing
"send -- "$kpxc_pw\r""
    (procedure "enter_pw" line 4)
    invoked from within
"enter_pw $kpxc_pw"
    (file "./keepassxc-dmenu" line 128)
`

**Comment by natrys** [comment]
> Invalid command open.

I am pretty sure now your keepassxc version is simply too old. The cli doesn't seem to have the interactive mode (`open` command, which this program needs). The interactive shell mode `open` command seems to have been added in [2.5.0](https://github.com/keepassxreboot/keepassxc/releases/tag/2.5.0).

Unfortunately this is one of the downsides of using stable distros like Debian/Deuvan. It didn't occur to me to make a note about this in the readme, I apologize for the inconvenience.

**Comment by EliaHKM** [comment]
OK thank you 
you are very helpful
have a good day
cheer
